---
seasons:
  - name: Corinthians
    start: Aug 1, 2025
    days: 365
    meets:

      - name: Welcome Event
        start: Sep 6 2025 8 AM PDT
        special_material: 1 Cor 1-2
        deadline: 0
        host:
            name: Dallas Alliance Church
            url: https://dallasalliance.org
            address: 775 E Ellendale Ave, Dallas OR 97338
        notes: No registration required

      - name: Meet 1
        region: WWA

      - name: Meet 2
        start: Nov 11 2025 8 AM PST
        new_material: 1 Cor 7-11

      - name: Meet 3
        start: Jan 24 2026 8 AM PST
        new_material: 1 Cor 12-16
