---
seasons:
  - name: Corinthians
    start: Aug 1, 2025
    days: 365
    meets:

      - name: Welcome Event
        start: Sep 6 2025 9 AM PDT
        special_material: 1 Cor 1
        deadline: 0
        host:
            name: Dallas Alliance Church
            url: https://dallasalliance.org
            address: 775 E Ellendale Ave, Dallas OR 97338
        notes: |
            - No registration required
            - [Additional Event Information Flyer](/2025-2026/welcome_event.md)

      - name: Meet 1
        start: Oct 11 2025 8 AM PDT
        new_material: 1 Cor 1-7
        host:
            name: Juniper Community Church
            url: https://junipercc.com
            address: 976 S Adams Dr, Madras OR 97741
            housing: true
            lunch: true

      - name: Meet 2
        region: WWA

      - name: Meet 3
        region: WWA

      - name: Meet 4
        region: WWA

      - name: Meet 5
        region: WWA

      - name: Championships
        region: WWA
